# Metadata for this documentation project.
# See https://quarto.orgpages/reference/projects/websites.html
project:
  type: website
  output-dir: _site

# Extensions
filters:
  - simple-vars # simple variable references: `{name}` instead of `{{< var name >}}`
  - admonitions # simpler callout blocks and alerts like AsciiDoc

format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: scroll
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 200px
      gutter-width: 1.5em
    theme:
      light:
        - cosmo
        - assets/css/theme.scss
        - assets/css/extras.scss
      dark:
        - cosmo
        - assets/css/theme.scss
        - assets/css/dark.scss
        - assets/css/extras.scss

website:
  title: "lulu"
  image: "assets/images/logo.png"
  favicon: "assets/images/logo.png"
  open-graph: true
  google-analytics: "G-DDG2B9HMD3"
  site-url: "https://nessan.github.io/lulu"
  repo-url: "https://github.com/nessan/lulu"
  repo-subdir: docs
  issue-url: "https://github.com/nessan/lulu/issues/new/choose"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    left: |
      &#169; 2025 Nessan &#8729; Made with [Quarto](https://quarto.org)
    center:
      - icon: github
        href: "https://github.com/nessan/lulu"
        aria-label: GitHub Repo
      - icon: envelope
        href: "mailto:nzznfitz+gh@icloud.com"
        aria-label: EMail address
    right: |
      [MIT Licensed](https://opensource.org/license/mit)

  navbar:
    background: dark
    logo: "assets/images/logo.png"
    logo-alt: "The utilities library logo"
    title: lulu
    search: true
    pinned: true
    collapse-below: lg
    left:
      - text: "Home"
        file: pages/index.qmd
      - text: "Classes"
        menu:
          - text: "Array"
            file: pages/Array/index.qmd
          - text: "Enum"
            file: pages/Enum/index.qmd
      - text: "Extensions"
        menu:
          - text: "Lua strings"
            file: pages/string/index.qmd
          - text: "Lua tables"
            file: pages/table/index.qmd
          - text: "The LPEG library"
            file: pages/lpeg/index.qmd
          - text: "Messages"
            file: pages/messages/index.qmd
      - text: "Lambdas"
        file: pages/callable/index.qmd
      - text: "Paths"
        file: pages/paths/index.qmd
      - text: "Types"
        file: pages/types/index.qmd
      - text: "Scribe"
        href: https://nessan.github.io/scribe
      - text: "Project"
        menu:
          - text: "Project Repo"
            icon: "github"
            href: "https://github.com/nessan/lulu"
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/nessan/lulu/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "mailto:nzznfitz+gh@icloud.com"
    tools:
      - icon: github
        href: "https://github.com/nessan/lulu"
        text: GitHub repo

  sidebar:
    style: floating
    type: light
    background: light
    align: left
    collapse-level: 2
    contents:
      - text: "Library Overview"
        file: pages/index.qmd
      - text: "The Array Class"
        file: pages/Array/index.qmd
      - text: "The Enum Class"
        file: pages/Enum/index.qmd
      - text: "Anonymous Functions"
        file: pages/callable/index.qmd
      - text: "Messages"
        file: pages/messages/index.qmd
      - text: "Path Utilities"
        file: pages/paths/index.qmd
      - text: "Type Utilities"
        file: pages/types/index.qmd
      - text: "Extensions: table"
        file: pages/table/index.qmd
      - text: "Extensions: string"
        file: pages/string/index.qmd
      - text: "Extensions: LPEG"
        file: pages/lpeg/index.qmd
      - text: "Scribe"
        href: https://nessan.github.io/scribe
